language: go
go: 1.8
go_import_path: github.com/safing/safing-core
dist: trusty
addons:
  apt:
    packages:
      - libnetfilter-queue-dev
install:
  - go get golang.org/x/crypto/chacha20poly1305
  - go get golang.org/x/net/icmp
script: ./test
