dist: trusty
language: go
go:
  - tip
addons:
  apt:
    packages:
    - libnetfilter-queue-dev
install:
- go get golang.org/x/crypto/chacha20poly1305
- go get golang.org/x/net/icmp
- go get github.com/mattn/goveralls
script:
- "./test travis-ci"
- $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
